define([
    './utils/form',
    './utils/focus',
    './utils/fromNow',
    './utils/avatarSelection',
    './utils/loadingText',
    './utils/countTo',
    './utils/typing',
    './compete/room-compete-directive',
    './compete/statistic/compete-statistic-directive',
    './topics/topic-factory',
    './topics/topic-service',
    './topics/topic-panel-directive',
    './topics/topic-commit-directive',
    './room/room-creation-controller',
    './room/room-service',
    './auth/users-service',
    './auth/auth-service',
    './users/user-list-directive',
    './users/profile/user-profile-directive',
    './chat/user-chat-directive',
    './navbar/navbar.controller',
    './modal/modal.service',
    './socketio/socket-service',
    './utils/message/message-center',
    './utils/message/comfirm'
], function () {
});

