define([
    './utils/form',
    './utils/focus',
    './utils/fromNow',
    './utils/comfirm',
    './utils/position',
    './compete/room-compete-directive',
    './topics/topic-factory',
    './topics/topic-service',
    './topics/topic-panel-directive',
    './topics/topic-commit-directive',
    './matches/match-stat-directive',
    './matches/match-stat-factory',
    './matches/multi/room-creation-directive',
    './matches/multi/room-service',
    './auth/users-service',
    './auth/auth-service',
    './users/online-list-directive',
    './chat/user-chat-directive',
    './navbar/navbar.controller',
    './modal/modal.service',
    './socketio/socket-service',
], function () {
});

